export enum ROLES {
  CUSTOMER = 'CUSTOMER',
  ADMIN = 'ADMIN',
  EMPLOYEE = 'EMPLOYEE',
  GUEST = 'GUEST',
}

export enum TRANSACTION_STATUS {
  PENDING = 'PENDING',
  FULFILLED = 'FULFILLED',
  REJECTED = 'REJECTED',
}

export enum PAYER {
  SENDER = 'SENDER',
  RECEIVER = 'RECEIVER',
}

export enum RECEIVER_TYPE {
  INTERNAL = 'INTERNAL',
  EXTERNAL = 'EXTERNAL',
}
